services:
  - type: web
    name: qlkhohang-backend
    env: docker
    plan: free
    dockerfilePath: server/Dockerfile  # chỉ rõ Dockerfile ở đâu
    rootDir: .                          # repo gốc, không phải "server"
    autoDeploy: true
    buildCommand: ""
    startCommand: ""
    envVars: []
