services:
  - type: web
    name: qlkhohang-backend
    env: docker
    plan: free
    dockerfilePath: server/Dockerfile
    rootDir: .
    autoDeploy: true

  - type: web
    name: qlkhohang-frontend
    env: node
    rootDir: .
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    envVars:
      - key: NODE_VERSION
        value: 18
