// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhoHangFPTShop.Data;

#nullable disable

namespace QLKhoHangFPTShop.Migrations
{
    [DbContext(typeof(WarehouseContext))]
    partial class WarehouseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cot", b =>
                {
                    b.Property<int>("idCot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCot"));

                    b.Property<int>("idDay")
                        .HasColumnType("int");

                    b.Property<string>("tenCot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCot");

                    b.HasIndex("idDay");

                    b.ToTable("Cot");
                });

            modelBuilder.Entity("Day", b =>
                {
                    b.Property<int>("idDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDay"));

                    b.Property<string>("tenDay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idDay");

                    b.ToTable("Day");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("idPhieuNhap")
                        .HasColumnType("int");

                    b.Property<int>("idSanPham")
                        .HasColumnType("int");

                    b.Property<decimal>("gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<int>("soLuong")
                        .HasColumnType("int");

                    b.HasKey("idPhieuNhap", "idSanPham");

                    b.HasIndex("idSanPham");

                    b.ToTable("ChiTietPhieuNhap");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ChiTietPhieuXuat", b =>
                {
                    b.Property<int>("idPhieuXuat")
                        .HasColumnType("int");

                    b.Property<int>("idSanPham")
                        .HasColumnType("int");

                    b.Property<int>("soLuong")
                        .HasColumnType("int");

                    b.HasKey("idPhieuXuat", "idSanPham");

                    b.HasIndex("idSanPham");

                    b.ToTable("ChiTietPhieuXuat");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ChiTietYeuCauXuatKho", b =>
                {
                    b.Property<int>("idYeuCauXuatKho")
                        .HasColumnType("int");

                    b.Property<int>("idSanPham")
                        .HasColumnType("int");

                    b.Property<int>("soLuong")
                        .HasColumnType("int");

                    b.HasKey("idYeuCauXuatKho", "idSanPham");

                    b.HasIndex("idSanPham");

                    b.ToTable("ChiTietYeuCauXuatKho");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ChucVu", b =>
                {
                    b.Property<int>("idChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idChucVu"));

                    b.Property<string>("moTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idChucVu");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.DaiLy", b =>
                {
                    b.Property<int>("idDaiLy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDaiLy"));

                    b.Property<string>("diaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenDaiLy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idDaiLy");

                    b.ToTable("DaiLy");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.DanhMuc", b =>
                {
                    b.Property<int>("idDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDanhMuc"));

                    b.Property<string>("tenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idDanhMuc");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.NhaCungCap", b =>
                {
                    b.Property<int>("idNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idNhaCungCap"));

                    b.Property<string>("diaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idPhuongXa")
                        .HasColumnType("int");

                    b.Property<string>("nhanVienLienHe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenNhaCungCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idNhaCungCap");

                    b.HasIndex("idPhuongXa");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.PhieuNhap", b =>
                {
                    b.Property<int>("idPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPhieuNhap"));

                    b.Property<int>("idNhaCungCap")
                        .HasColumnType("int");

                    b.Property<int>("idTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayNhap")
                        .HasColumnType("datetime2");

                    b.HasKey("idPhieuNhap");

                    b.HasIndex("idNhaCungCap");

                    b.HasIndex("idTaiKhoan");

                    b.ToTable("PhieuNhap", (string)null);
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.PhieuXuat", b =>
                {
                    b.Property<int>("idPhieuXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPhieuXuat"));

                    b.Property<int>("idYeuCauXuatKho")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayXuat")
                        .HasColumnType("datetime2");

                    b.HasKey("idPhieuXuat");

                    b.HasIndex("idYeuCauXuatKho");

                    b.ToTable("PhieuXuat");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.PhuongXa", b =>
                {
                    b.Property<int>("idPhuongXa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPhuongXa"));

                    b.Property<int>("idQuanHuyen")
                        .HasColumnType("int");

                    b.Property<string>("tenPhuongXa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPhuongXa");

                    b.HasIndex("idQuanHuyen");

                    b.ToTable("PhuongXa");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.QuanHuyen", b =>
                {
                    b.Property<int>("idQuanHuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idQuanHuyen"));

                    b.Property<int>("idTinhThanh")
                        .HasColumnType("int");

                    b.Property<string>("tenQuanHuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idQuanHuyen");

                    b.HasIndex("idTinhThanh");

                    b.ToTable("QuanHuyen");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.SanPham", b =>
                {
                    b.Property<int>("idSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSanPham"));

                    b.Property<decimal>("chieuCao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("chieuDai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("chieuRong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("donGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("idDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("idNhaCungCap")
                        .HasColumnType("int");

                    b.Property<int>("idThuongHieu")
                        .HasColumnType("int");

                    b.Property<int>("idViTri")
                        .HasColumnType("int");

                    b.Property<decimal>("khoiLuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("mauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("moTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngaySanXuat")
                        .HasColumnType("datetime2");

                    b.Property<string>("sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("soLuongHienCon")
                        .HasColumnType("int");

                    b.Property<int>("soLuongToiThieu")
                        .HasColumnType("int");

                    b.Property<string>("tenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idSanPham");

                    b.HasIndex("idDanhMuc");

                    b.HasIndex("idNhaCungCap");

                    b.HasIndex("idThuongHieu");

                    b.HasIndex("idViTri");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.SanPham_ThongSo", b =>
                {
                    b.Property<int>("idSanPham")
                        .HasColumnType("int");

                    b.Property<int>("idThongSo")
                        .HasColumnType("int");

                    b.Property<string>("giaTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idThongSoKyThuat")
                        .HasColumnType("int");

                    b.HasKey("idSanPham", "idThongSo");

                    b.HasIndex("idThongSoKyThuat");

                    b.ToTable("SanPham_ThongSo");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.TaiKhoan", b =>
                {
                    b.Property<int>("idTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTaiKhoan"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idChucVu")
                        .HasColumnType("int");

                    b.Property<string>("matKhau")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ngayCap")
                        .HasColumnType("datetime2");

                    b.Property<string>("tenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("trangThai")
                        .HasColumnType("bit");

                    b.HasKey("idTaiKhoan");

                    b.HasIndex("idChucVu");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ThongSoKyThuat", b =>
                {
                    b.Property<int>("idThongSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idThongSo"));

                    b.Property<string>("tenThongSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idThongSo");

                    b.ToTable("ThongSoKyThuat");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ThuongHieu", b =>
                {
                    b.Property<int>("idThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idThuongHieu"));

                    b.Property<string>("tenThuongHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idThuongHieu");

                    b.ToTable("ThuongHieu");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.TinhThanh", b =>
                {
                    b.Property<int>("idTinhThanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTinhThanh"));

                    b.Property<string>("tenTinhThanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTinhThanh");

                    b.ToTable("TinhThanh");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.TrangThaiXacNhan", b =>
                {
                    b.Property<int>("idTrangThaiXacNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTrangThaiXacNhan"));

                    b.Property<string>("tenTrangThaiXacNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTrangThaiXacNhan");

                    b.ToTable("TrangThaiXacNhan");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.YeuCauXuatKho", b =>
                {
                    b.Property<int>("idYeuCauXuatKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idYeuCauXuatKho"));

                    b.Property<int?>("idDaiLy")
                        .HasColumnType("int");

                    b.Property<int>("idTrangThaiXacNhan")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayYeuCau")
                        .HasColumnType("datetime2");

                    b.HasKey("idYeuCauXuatKho");

                    b.HasIndex("idDaiLy");

                    b.HasIndex("idTrangThaiXacNhan");

                    b.ToTable("YeuCauXuatKho");
                });

            modelBuilder.Entity("Tang", b =>
                {
                    b.Property<int>("idTang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTang"));

                    b.Property<int>("idCot")
                        .HasColumnType("int");

                    b.Property<string>("tenTang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTang");

                    b.HasIndex("idCot");

                    b.ToTable("Tang");
                });

            modelBuilder.Entity("ViTri", b =>
                {
                    b.Property<int>("idViTri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idViTri"));

                    b.Property<decimal>("chieuCao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("chieuDai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("chieuRong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("idTang")
                        .HasColumnType("int");

                    b.Property<decimal>("theTich")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("trangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idViTri");

                    b.HasIndex("idTang");

                    b.ToTable("ViTri");
                });

            modelBuilder.Entity("Cot", b =>
                {
                    b.HasOne("Day", "Day")
                        .WithMany()
                        .HasForeignKey("idDay")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("idPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhap");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ChiTietPhieuXuat", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.PhieuXuat", "PhieuXuat")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("idPhieuXuat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuXuat");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ChiTietYeuCauXuatKho", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.YeuCauXuatKho", "YeuCauXuatKho")
                        .WithMany("ChiTietYeuCauXuatKhos")
                        .HasForeignKey("idYeuCauXuatKho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("YeuCauXuatKho");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.NhaCungCap", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.PhuongXa", "PhuongXa")
                        .WithMany()
                        .HasForeignKey("idPhuongXa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhuongXa");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.PhieuNhap", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("idNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("idTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.PhieuXuat", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.YeuCauXuatKho", "YeuCauXuatKho")
                        .WithMany()
                        .HasForeignKey("idYeuCauXuatKho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YeuCauXuatKho");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.PhuongXa", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.QuanHuyen", "QuanHuyen")
                        .WithMany()
                        .HasForeignKey("idQuanHuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuanHuyen");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.QuanHuyen", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.TinhThanh", "TinhThanh")
                        .WithMany()
                        .HasForeignKey("idTinhThanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TinhThanh");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.SanPham", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.DanhMuc", "DanhMuc")
                        .WithMany()
                        .HasForeignKey("idDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("idNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.ThuongHieu", "ThuongHieu")
                        .WithMany()
                        .HasForeignKey("idThuongHieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViTri", "ViTri")
                        .WithMany()
                        .HasForeignKey("idViTri")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("NhaCungCap");

                    b.Navigation("ThuongHieu");

                    b.Navigation("ViTri");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.SanPham_ThongSo", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.ThongSoKyThuat", "ThongSoKyThuat")
                        .WithMany()
                        .HasForeignKey("idThongSoKyThuat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("ThongSoKyThuat");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.ChucVu", "ChucVu")
                        .WithMany()
                        .HasForeignKey("idChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.YeuCauXuatKho", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.DaiLy", "DaiLy")
                        .WithMany()
                        .HasForeignKey("idDaiLy");

                    b.HasOne("QuanLyKhoHangFPTShop.Models.TrangThaiXacNhan", "TrangThaiXacNhan")
                        .WithMany()
                        .HasForeignKey("idTrangThaiXacNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaiLy");

                    b.Navigation("TrangThaiXacNhan");
                });

            modelBuilder.Entity("Tang", b =>
                {
                    b.HasOne("Cot", "Cot")
                        .WithMany()
                        .HasForeignKey("idCot")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cot");
                });

            modelBuilder.Entity("ViTri", b =>
                {
                    b.HasOne("Tang", "Tang")
                        .WithMany()
                        .HasForeignKey("idTang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tang");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.PhieuXuat", b =>
                {
                    b.Navigation("ChiTietPhieuXuats");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.YeuCauXuatKho", b =>
                {
                    b.Navigation("ChiTietYeuCauXuatKhos");
                });
#pragma warning restore 612, 618
        }
    }
}
