// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhoHangFPTShop.server.Data;

#nullable disable

namespace QuanLyKhoHangFPTShop.Migrations
{
    [DbContext(typeof(WarehouseContext))]
    [Migration("20250512151800_UpdateSucChuaToDecimal20")]
    partial class UpdateSucChuaToDecimal20
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("idPhieuNhap")
                        .HasColumnType("int");

                    b.Property<int>("idSanPham")
                        .HasColumnType("int");

                    b.Property<decimal>("donGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("nguoiGiaoHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("soLuongTheoChungTu")
                        .HasColumnType("int");

                    b.Property<int>("soLuongThucNhap")
                        .HasColumnType("int");

                    b.Property<decimal>("tongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("trangThai")
                        .HasColumnType("int");

                    b.HasKey("idPhieuNhap", "idSanPham");

                    b.HasIndex("idSanPham");

                    b.ToTable("ChiTietPhieuNhap");
                });

            modelBuilder.Entity("DonViTinh", b =>
                {
                    b.Property<int>("idDonViTinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDonViTinh"));

                    b.Property<string>("tenDonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idDonViTinh");

                    b.ToTable("DonViTinh");
                });

            modelBuilder.Entity("PhieuXuat", b =>
                {
                    b.Property<int>("IdPhieuXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPhieuXuat");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPhieuXuat"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghiChu");

                    b.Property<int?>("IdYeuCauXuatKho")
                        .HasColumnType("int")
                        .HasColumnName("idYeuCauXuatKho");

                    b.Property<string>("MaPhieu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("maPhieu");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXuat");

                    b.Property<string>("NguoiXuat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoiXuat");

                    b.HasKey("IdPhieuXuat");

                    b.HasIndex("IdYeuCauXuatKho");

                    b.ToTable("PhieuXuat");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ChiTietKiemKe", b =>
                {
                    b.Property<int>("idKiemKe")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("idSanPham")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("idViTri")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<string>("phamChat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("soLuongTheoHeThong")
                        .HasColumnType("int");

                    b.Property<int>("soLuongThucTe")
                        .HasColumnType("int");

                    b.HasKey("idKiemKe", "idSanPham");

                    b.HasIndex("idSanPham");

                    b.HasIndex("idViTri");

                    b.ToTable("ChiTietKiemKe");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ChiTietLuuTru", b =>
                {
                    b.Property<int>("idChiTietLuuTru")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idChiTietLuuTru"));

                    b.Property<int>("idSanPham")
                        .HasColumnType("int");

                    b.Property<int>("idViTri")
                        .HasColumnType("int");

                    b.Property<int>("soLuong")
                        .HasColumnType("int");

                    b.Property<DateTime>("thoiGianLuu")
                        .HasColumnType("datetime2");

                    b.HasKey("idChiTietLuuTru");

                    b.HasIndex("idSanPham");

                    b.HasIndex("idViTri");

                    b.ToTable("ChiTietLuuTru");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ChiTietPhieuXuat", b =>
                {
                    b.Property<int>("IdPhieuXuat")
                        .HasColumnType("int")
                        .HasColumnName("idPhieuXuat");

                    b.Property<int>("IdSanPham")
                        .HasColumnType("int")
                        .HasColumnName("idSanPham");

                    b.Property<int>("IdViTri")
                        .HasColumnType("int")
                        .HasColumnName("idViTri");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("soLuong");

                    b.HasKey("IdPhieuXuat", "IdSanPham", "IdViTri");

                    b.HasIndex("IdSanPham");

                    b.HasIndex("IdViTri");

                    b.ToTable("ChiTietPhieuXuat");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ChiTietThongSoKyThuat", b =>
                {
                    b.Property<int>("idSanPham")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("idThongSo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("giaTriThongSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idSanPham", "idThongSo");

                    b.HasIndex("idThongSo");

                    b.ToTable("ChiTietThongSoKyThuat");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ChiTietYeuCauKiemKe", b =>
                {
                    b.Property<int>("idYeuCauKiemKe")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("idSanPham")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("idYeuCauKiemKe", "idSanPham");

                    b.HasIndex("idSanPham");

                    b.ToTable("ChiTietYeuCauKiemKe");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ChiTietYeuCauXuatKho", b =>
                {
                    b.Property<int>("idYeuCauXuatKho")
                        .HasColumnType("int");

                    b.Property<int>("idSanPham")
                        .HasColumnType("int");

                    b.Property<int>("soLuong")
                        .HasColumnType("int");

                    b.HasKey("idYeuCauXuatKho", "idSanPham");

                    b.HasIndex("idSanPham");

                    b.ToTable("ChiTietYeuCauXuatKho");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ChucVu", b =>
                {
                    b.Property<int>("idChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idChucVu"));

                    b.Property<string>("moTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idChucVu");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.DaiLy", b =>
                {
                    b.Property<int>("idDaiLy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDaiLy"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDaiLy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idDaiLy");

                    b.ToTable("DaiLy");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.DanhMuc", b =>
                {
                    b.Property<int>("idDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDanhMuc"));

                    b.Property<string>("tenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idDanhMuc");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.KhuVuc", b =>
                {
                    b.Property<int>("idKhuVuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idKhuVuc"));

                    b.Property<string>("loaiKhuVuc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("tenKhuVuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idKhuVuc");

                    b.ToTable("KhuVuc");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.KiemKe", b =>
                {
                    b.Property<int>("idKiemKe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idKiemKe"));

                    b.Property<string>("ghiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idNguoiThucHien")
                        .HasColumnType("int");

                    b.Property<int>("idYeuCauKiemKe")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayKiemKe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("thoiGianThucHien")
                        .HasColumnType("datetime2");

                    b.HasKey("idKiemKe");

                    b.HasIndex("idYeuCauKiemKe");

                    b.ToTable("KiemKe");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.LoHang", b =>
                {
                    b.Property<int>("idLoHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLoHang"));

                    b.Property<int>("idNhaCungCap")
                        .HasColumnType("int");

                    b.Property<int>("idPhieuNhap")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayNhapLo")
                        .HasColumnType("datetime2");

                    b.Property<string>("tenLo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trangThaiLoHang")
                        .HasColumnType("int");

                    b.HasKey("idLoHang");

                    b.HasIndex("idNhaCungCap");

                    b.HasIndex("idPhieuNhap");

                    b.ToTable("LoHang");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.NhaCungCap", b =>
                {
                    b.Property<int>("idNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idNhaCungCap"));

                    b.Property<string>("diaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idPhuongXa")
                        .HasColumnType("int");

                    b.Property<string>("nhanVienLienHe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenNhaCungCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idNhaCungCap");

                    b.HasIndex("idPhuongXa");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.PhieuNhap", b =>
                {
                    b.Property<int>("idPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPhieuNhap"));

                    b.Property<int>("idNhaCungCap")
                        .HasColumnType("int");

                    b.Property<int>("idTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayNhap")
                        .HasColumnType("datetime2");

                    b.HasKey("idPhieuNhap");

                    b.HasIndex("idNhaCungCap");

                    b.HasIndex("idTaiKhoan");

                    b.ToTable("PhieuNhap", (string)null);
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.PhuongXa", b =>
                {
                    b.Property<int>("idPhuongXa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPhuongXa"));

                    b.Property<int>("idQuanHuyen")
                        .HasColumnType("int");

                    b.Property<string>("tenPhuongXa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPhuongXa");

                    b.HasIndex("idQuanHuyen");

                    b.ToTable("PhuongXa");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.QuanHuyen", b =>
                {
                    b.Property<int>("idQuanHuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idQuanHuyen"));

                    b.Property<int>("idTinhThanh")
                        .HasColumnType("int");

                    b.Property<string>("tenQuanHuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idQuanHuyen");

                    b.HasIndex("idTinhThanh");

                    b.ToTable("QuanHuyen");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.SanPham", b =>
                {
                    b.Property<int>("idSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSanPham"));

                    b.Property<decimal?>("chieuCao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("chieuDai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("chieuRong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("donGiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("idDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("idDonViTinh")
                        .HasColumnType("int");

                    b.Property<int>("idNhaCungCap")
                        .HasColumnType("int");

                    b.Property<int>("idThuongHieu")
                        .HasColumnType("int");

                    b.Property<decimal>("khoiLuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("mauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("moTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngaySanXuat")
                        .HasColumnType("datetime2");

                    b.Property<string>("sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("soLuongHienCon")
                        .HasColumnType("int");

                    b.Property<int>("soLuongToiThieu")
                        .HasColumnType("int");

                    b.Property<string>("tenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idSanPham");

                    b.HasIndex("idDanhMuc");

                    b.HasIndex("idDonViTinh");

                    b.HasIndex("idNhaCungCap");

                    b.HasIndex("idThuongHieu");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.SanPham_ThongSo", b =>
                {
                    b.Property<int>("idSanPham")
                        .HasColumnType("int");

                    b.Property<int>("idThongSo")
                        .HasColumnType("int");

                    b.Property<string>("giaTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idThongSoKyThuat")
                        .HasColumnType("int");

                    b.HasKey("idSanPham", "idThongSo");

                    b.HasIndex("idThongSoKyThuat");

                    b.ToTable("SanPham_ThongSo");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.TaiKhoan", b =>
                {
                    b.Property<int>("idTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTaiKhoan"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idChucVu")
                        .HasColumnType("int");

                    b.Property<string>("matKhau")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ngayCap")
                        .HasColumnType("datetime2");

                    b.Property<string>("tenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("trangThai")
                        .HasColumnType("bit");

                    b.HasKey("idTaiKhoan");

                    b.HasIndex("idChucVu");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ThongSoKyThuat", b =>
                {
                    b.Property<int>("idThongSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idThongSo"));

                    b.Property<string>("tenThongSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idThongSo");

                    b.ToTable("ThongSoKyThuat");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ThuongHieu", b =>
                {
                    b.Property<int>("idThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idThuongHieu"));

                    b.Property<string>("tenThuongHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idThuongHieu");

                    b.ToTable("ThuongHieu");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.TinhThanh", b =>
                {
                    b.Property<int>("idTinhThanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTinhThanh"));

                    b.Property<string>("tenTinhThanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTinhThanh");

                    b.ToTable("TinhThanh");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.TrangThaiXacNhan", b =>
                {
                    b.Property<int>("idTrangThaiXacNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTrangThaiXacNhan"));

                    b.Property<string>("tenTrangThaiXacNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTrangThaiXacNhan");

                    b.ToTable("TrangThaiXacNhan");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ViTri", b =>
                {
                    b.Property<int>("IdViTri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdViTri"));

                    b.Property<int>("Cot")
                        .HasColumnType("int");

                    b.Property<int>("DaDung")
                        .HasColumnType("int");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("SucChua")
                        .HasColumnType("decimal(20, 2)");

                    b.Property<int>("Tang")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("chieuCao")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("chieuDai")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("chieuRong")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("idKhuVuc")
                        .HasColumnType("int");

                    b.HasKey("IdViTri");

                    b.HasIndex("idKhuVuc");

                    b.ToTable("ViTri");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.YeuCauKiemKe", b =>
                {
                    b.Property<int>("idYeuCauKiemKe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idYeuCauKiemKe"));

                    b.Property<string>("ghiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("mucDich")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ngayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("nguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("tenTruongBan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("tenUyVien1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("tenUyVien2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("trangThai")
                        .HasColumnType("int");

                    b.Property<string>("viTriKiemKe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idYeuCauKiemKe");

                    b.HasIndex("nguoiTao");

                    b.ToTable("YeuCauKiemKe");
                });

            modelBuilder.Entity("YeuCauXuatKho", b =>
                {
                    b.Property<int>("IdYeuCauXuatKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idYeuCauXuatKho");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdYeuCauXuatKho"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("diaChi");

                    b.Property<string>("HinhThucXuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hinhThucXuat");

                    b.Property<int>("IdDaiLy")
                        .HasColumnType("int")
                        .HasColumnName("idDaiLy");

                    b.Property<int>("IdDanhMuc")
                        .HasColumnType("int")
                        .HasColumnName("idDanhMuc");

                    b.Property<int>("IdDonViTinh")
                        .HasColumnType("int")
                        .HasColumnName("idDonViTinh");

                    b.Property<int>("IdTrangThaiXacNhan")
                        .HasColumnType("int")
                        .HasColumnName("idTrangThaiXacNhan");

                    b.Property<string>("LyDoXuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lyDoXuat");

                    b.Property<string>("MaPhieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("maPhieu");

                    b.Property<DateTime>("NgayYeuCau")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayYeuCau");

                    b.Property<string>("NguoiYeuCau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoiYeuCau");

                    b.Property<string>("PhuongThucVanChuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phuongThucVanChuyen");

                    b.HasKey("IdYeuCauXuatKho");

                    b.HasIndex("IdDaiLy");

                    b.HasIndex("IdDanhMuc");

                    b.HasIndex("IdDonViTinh");

                    b.HasIndex("IdTrangThaiXacNhan");

                    b.ToTable("YeuCauXuatKho");
                });

            modelBuilder.Entity("ChiTietPhieuNhap", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPhieuNhap")
                        .HasForeignKey("idPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhap");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("PhieuXuat", b =>
                {
                    b.HasOne("YeuCauXuatKho", "YeuCauXuatKho")
                        .WithMany()
                        .HasForeignKey("IdYeuCauXuatKho");

                    b.Navigation("YeuCauXuatKho");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ChiTietKiemKe", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.KiemKe", "KiemKe")
                        .WithMany("ChiTietKiemKe")
                        .HasForeignKey("idKiemKe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.ViTri", "ViTri")
                        .WithMany()
                        .HasForeignKey("idViTri")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KiemKe");

                    b.Navigation("SanPham");

                    b.Navigation("ViTri");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ChiTietLuuTru", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.ViTri", "ViTri")
                        .WithMany()
                        .HasForeignKey("idViTri")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("ViTri");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ChiTietPhieuXuat", b =>
                {
                    b.HasOne("PhieuXuat", "PhieuXuat")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("IdPhieuXuat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("IdSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.ViTri", "ViTri")
                        .WithMany()
                        .HasForeignKey("IdViTri")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuXuat");

                    b.Navigation("SanPham");

                    b.Navigation("ViTri");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ChiTietThongSoKyThuat", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.ThongSoKyThuat", "ThongSoKyThuat")
                        .WithMany("ChiTietThongSoKyThuat")
                        .HasForeignKey("idThongSo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("ThongSoKyThuat");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ChiTietYeuCauKiemKe", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.YeuCauKiemKe", "YeuCauKiemKe")
                        .WithMany("ChiTietYeuCau")
                        .HasForeignKey("idYeuCauKiemKe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("YeuCauKiemKe");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ChiTietYeuCauXuatKho", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YeuCauXuatKho", "YeuCauXuatKho")
                        .WithMany("ChiTietYeuCauXuatKhos")
                        .HasForeignKey("idYeuCauXuatKho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("YeuCauXuatKho");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.KiemKe", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.YeuCauKiemKe", "YeuCauKiemKe")
                        .WithMany()
                        .HasForeignKey("idYeuCauKiemKe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YeuCauKiemKe");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.LoHang", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("idNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.PhieuNhap", "PhieuNhap")
                        .WithMany()
                        .HasForeignKey("idPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.NhaCungCap", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.PhuongXa", "PhuongXa")
                        .WithMany()
                        .HasForeignKey("idPhuongXa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhuongXa");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.PhieuNhap", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("idNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("idTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.PhuongXa", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.QuanHuyen", "QuanHuyen")
                        .WithMany()
                        .HasForeignKey("idQuanHuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuanHuyen");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.QuanHuyen", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.TinhThanh", "TinhThanh")
                        .WithMany()
                        .HasForeignKey("idTinhThanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TinhThanh");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.SanPham", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.DanhMuc", "DanhMuc")
                        .WithMany()
                        .HasForeignKey("idDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DonViTinh", "DonViTinh")
                        .WithMany()
                        .HasForeignKey("idDonViTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("idNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.ThuongHieu", "ThuongHieu")
                        .WithMany()
                        .HasForeignKey("idThuongHieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("DonViTinh");

                    b.Navigation("NhaCungCap");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.SanPham_ThongSo", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.ThongSoKyThuat", "ThongSoKyThuat")
                        .WithMany()
                        .HasForeignKey("idThongSoKyThuat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("ThongSoKyThuat");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.ChucVu", "ChucVu")
                        .WithMany()
                        .HasForeignKey("idChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ViTri", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.KhuVuc", "KhuVuc")
                        .WithMany("ViTris")
                        .HasForeignKey("idKhuVuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuVuc");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.YeuCauKiemKe", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.TaiKhoan", "NguoiTaoTaiKhoan")
                        .WithMany()
                        .HasForeignKey("nguoiTao");

                    b.Navigation("NguoiTaoTaiKhoan");
                });

            modelBuilder.Entity("YeuCauXuatKho", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.Models.DaiLy", "DaiLy")
                        .WithMany()
                        .HasForeignKey("IdDaiLy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.DanhMuc", "DanhMuc")
                        .WithMany()
                        .HasForeignKey("IdDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DonViTinh", "DonViTinh")
                        .WithMany()
                        .HasForeignKey("IdDonViTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.Models.TrangThaiXacNhan", "TrangThaiXacNhan")
                        .WithMany()
                        .HasForeignKey("IdTrangThaiXacNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaiLy");

                    b.Navigation("DanhMuc");

                    b.Navigation("DonViTinh");

                    b.Navigation("TrangThaiXacNhan");
                });

            modelBuilder.Entity("PhieuXuat", b =>
                {
                    b.Navigation("ChiTietPhieuXuats");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.KhuVuc", b =>
                {
                    b.Navigation("ViTris");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.KiemKe", b =>
                {
                    b.Navigation("ChiTietKiemKe");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhap");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.ThongSoKyThuat", b =>
                {
                    b.Navigation("ChiTietThongSoKyThuat");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.Models.YeuCauKiemKe", b =>
                {
                    b.Navigation("ChiTietYeuCau");
                });

            modelBuilder.Entity("YeuCauXuatKho", b =>
                {
                    b.Navigation("ChiTietYeuCauXuatKhos");
                });
#pragma warning restore 612, 618
        }
    }
}
