// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhoHangFPTShop.server.Data;

#nullable disable

namespace QuanLyKhoHangFPTShop.Migrations
{
    [DbContext(typeof(WarehouseContext))]
    [Migration("20250617171058_AddViTriLuuTam")]
    partial class AddViTriLuuTam
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("idPhieuNhap")
                        .HasColumnType("int");

                    b.Property<int>("idSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("PhieuNhapidPhieuNhap")
                        .HasColumnType("int");

                    b.Property<decimal>("donGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("nguoiGiaoHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("soLuongTheoChungTu")
                        .HasColumnType("int");

                    b.Property<int>("soLuongThucNhap")
                        .HasColumnType("int");

                    b.Property<decimal>("tongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("trangThai")
                        .HasColumnType("int");

                    b.HasKey("idPhieuNhap", "idSanPham");

                    b.HasIndex("PhieuNhapidPhieuNhap");

                    b.HasIndex("idSanPham");

                    b.ToTable("CHITIETPHIEUNHAP");
                });

            modelBuilder.Entity("DonViTinh", b =>
                {
                    b.Property<int>("idDonViTinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDonViTinh"));

                    b.Property<string>("tenDonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idDonViTinh");

                    b.ToTable("DONVITINH");
                });

            modelBuilder.Entity("PhieuXuat", b =>
                {
                    b.Property<int>("IdPhieuXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPhieuXuat");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPhieuXuat"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghiChu");

                    b.Property<int?>("IdYeuCauXuatKho")
                        .HasColumnType("int")
                        .HasColumnName("idYeuCauXuatKho");

                    b.Property<string>("MaPhieu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("maPhieu");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXuat");

                    b.Property<string>("NguoiXuat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoiXuat");

                    b.HasKey("IdPhieuXuat");

                    b.HasIndex("IdYeuCauXuatKho");

                    b.ToTable("PHIEUXUAT");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ChiTietKiemKe", b =>
                {
                    b.Property<int>("idKiemKe")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("idSanPham")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("idViTri")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<string>("ghiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phamChat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("soLuongTheoHeThong")
                        .HasColumnType("int");

                    b.Property<int>("soLuongThucTe")
                        .HasColumnType("int");

                    b.HasKey("idKiemKe", "idSanPham", "idViTri");

                    b.HasIndex("idSanPham");

                    b.HasIndex("idViTri");

                    b.ToTable("CHITIETKIEMKE");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ChiTietLuuTru", b =>
                {
                    b.Property<int>("idChiTietLuuTru")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idChiTietLuuTru"));

                    b.Property<int?>("idLoHang")
                        .HasColumnType("int");

                    b.Property<int>("idPhieuNhap")
                        .HasColumnType("int");

                    b.Property<int>("idSanPham")
                        .HasColumnType("int");

                    b.Property<int>("idViTri")
                        .HasColumnType("int");

                    b.Property<int>("soLuong")
                        .HasColumnType("int");

                    b.Property<DateTime>("thoiGianLuu")
                        .HasColumnType("datetime2");

                    b.HasKey("idChiTietLuuTru");

                    b.HasIndex("idLoHang");

                    b.HasIndex("idPhieuNhap");

                    b.HasIndex("idSanPham");

                    b.HasIndex("idViTri");

                    b.ToTable("CHITIETLUUTRU");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ChiTietPhieuXuat", b =>
                {
                    b.Property<int>("IdPhieuXuat")
                        .HasColumnType("int")
                        .HasColumnName("idPhieuXuat");

                    b.Property<int>("IdSanPham")
                        .HasColumnType("int")
                        .HasColumnName("idSanPham");

                    b.Property<int>("IdViTri")
                        .HasColumnType("int")
                        .HasColumnName("idViTri");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("soLuong");

                    b.Property<decimal?>("chietKhau")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("donGiaXuat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("giaSauChietKhau")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("tongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPhieuXuat", "IdSanPham", "IdViTri");

                    b.HasIndex("IdSanPham");

                    b.HasIndex("IdViTri");

                    b.ToTable("CHITIETPHIEUXUAT");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ChiTietThongSoKyThuat", b =>
                {
                    b.Property<int>("idSanPham")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("idThongSo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("giaTriThongSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idSanPham", "idThongSo");

                    b.HasIndex("idThongSo");

                    b.ToTable("CHITIETTHONGSOKYTHUAT");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ChiTietYeuCauKiemKe", b =>
                {
                    b.Property<int>("idYeuCauKiemKe")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("idSanPham")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("idYeuCauKiemKe", "idSanPham");

                    b.HasIndex("idSanPham");

                    b.ToTable("CHITIETYEUCAUKIEMKE");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ChiTietYeuCauXuatKho", b =>
                {
                    b.Property<int>("idYeuCauXuatKho")
                        .HasColumnType("int");

                    b.Property<int>("idSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("YeuCauXuatKhoIdYeuCauXuatKho")
                        .HasColumnType("int");

                    b.Property<int>("soLuong")
                        .HasColumnType("int");

                    b.HasKey("idYeuCauXuatKho", "idSanPham");

                    b.HasIndex("YeuCauXuatKhoIdYeuCauXuatKho");

                    b.HasIndex("idSanPham");

                    b.ToTable("CHITIETYEUCAUXUATKHO");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ChucVu", b =>
                {
                    b.Property<int>("idChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idChucVu"));

                    b.Property<string>("moTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idChucVu");

                    b.ToTable("CHUCVU");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.DaiLy", b =>
                {
                    b.Property<int>("idDaiLy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDaiLy"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDaiLy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idDaiLy");

                    b.ToTable("DAILY");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.DanhMuc", b =>
                {
                    b.Property<int>("idDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDanhMuc"));

                    b.Property<string>("tenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idDanhMuc");

                    b.ToTable("DANHMUC");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.KhuVuc", b =>
                {
                    b.Property<int>("idKhuVuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idKhuVuc"));

                    b.Property<string>("loaiKhuVuc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("tenKhuVuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idKhuVuc");

                    b.ToTable("KHUVUC");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.KiemKe", b =>
                {
                    b.Property<int>("idKiemKe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idKiemKe"));

                    b.Property<string>("ghiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idNguoiThucHien")
                        .HasColumnType("int");

                    b.Property<int>("idYeuCauKiemKe")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayKiemKe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("thoiGianThucHien")
                        .HasColumnType("datetime2");

                    b.Property<int>("trangThai")
                        .HasColumnType("int");

                    b.HasKey("idKiemKe");

                    b.HasIndex("idYeuCauKiemKe");

                    b.ToTable("KIEMKE");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.LoHang", b =>
                {
                    b.Property<int>("idLoHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLoHang"));

                    b.Property<int>("idNhaCungCap")
                        .HasColumnType("int");

                    b.Property<int>("idPhieuNhap")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayNhapLo")
                        .HasColumnType("datetime2");

                    b.Property<string>("tenLo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trangThaiLoHang")
                        .HasColumnType("int");

                    b.HasKey("idLoHang");

                    b.HasIndex("idNhaCungCap");

                    b.HasIndex("idPhieuNhap");

                    b.ToTable("LOHANG");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.NhaCungCap", b =>
                {
                    b.Property<int>("idNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idNhaCungCap"));

                    b.Property<string>("diaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idPhuongXa")
                        .HasColumnType("int");

                    b.Property<string>("nhanVienLienHe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenNhaCungCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idNhaCungCap");

                    b.HasIndex("idPhuongXa");

                    b.ToTable("NHACUNGCAP");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.PhieuNhap", b =>
                {
                    b.Property<int>("idPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPhieuNhap"));

                    b.Property<int>("idNhaCungCap")
                        .HasColumnType("int");

                    b.Property<int>("idTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayNhap")
                        .HasColumnType("datetime2");

                    b.HasKey("idPhieuNhap");

                    b.HasIndex("idNhaCungCap");

                    b.HasIndex("idTaiKhoan");

                    b.ToTable("PHIEUNHAP");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.PhuongXa", b =>
                {
                    b.Property<int>("idPhuongXa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPhuongXa"));

                    b.Property<int>("idQuanHuyen")
                        .HasColumnType("int");

                    b.Property<string>("tenPhuongXa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPhuongXa");

                    b.HasIndex("idQuanHuyen");

                    b.ToTable("PHUONGXA");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.QuanHuyen", b =>
                {
                    b.Property<int>("idQuanHuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idQuanHuyen"));

                    b.Property<int>("idTinhThanh")
                        .HasColumnType("int");

                    b.Property<string>("tenQuanHuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idQuanHuyen");

                    b.HasIndex("idTinhThanh");

                    b.ToTable("QUANHUYEN");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.SanPham", b =>
                {
                    b.Property<int>("idSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSanPham"));

                    b.Property<decimal?>("chieuCao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("chieuDai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("chieuRong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("donGiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("hinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("idDonViTinh")
                        .HasColumnType("int");

                    b.Property<int>("idNhaCungCap")
                        .HasColumnType("int");

                    b.Property<int>("idThuongHieu")
                        .HasColumnType("int");

                    b.Property<decimal>("khoiLuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("mauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("moTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngaySanXuat")
                        .HasColumnType("datetime2");

                    b.Property<string>("sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("soLuongHienCon")
                        .HasColumnType("int");

                    b.Property<int>("soLuongToiThieu")
                        .HasColumnType("int");

                    b.Property<string>("tenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idSanPham");

                    b.HasIndex("idDanhMuc");

                    b.HasIndex("idDonViTinh");

                    b.HasIndex("idNhaCungCap");

                    b.HasIndex("idThuongHieu");

                    b.ToTable("SANPHAM");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.SanPham_ThongSo", b =>
                {
                    b.Property<int>("idSanPham")
                        .HasColumnType("int");

                    b.Property<int>("idThongSo")
                        .HasColumnType("int");

                    b.Property<string>("giaTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idThongSoKyThuat")
                        .HasColumnType("int");

                    b.HasKey("idSanPham", "idThongSo");

                    b.HasIndex("idThongSoKyThuat");

                    b.ToTable("SANPHAMTHONGSO");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.TaiKhoan", b =>
                {
                    b.Property<int>("idTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTaiKhoan"));

                    b.Property<bool?>("doiMatKhau")
                        .HasColumnType("bit");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idChucVu")
                        .HasColumnType("int");

                    b.Property<int?>("idDaiLy")
                        .HasColumnType("int");

                    b.Property<string>("matKhau")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ngayCap")
                        .HasColumnType("datetime2");

                    b.Property<string>("resetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("resetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("tenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("trangThai")
                        .HasColumnType("bit");

                    b.HasKey("idTaiKhoan");

                    b.HasIndex("idChucVu");

                    b.HasIndex("idDaiLy");

                    b.ToTable("TAIKHOAN");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ThongBao", b =>
                {
                    b.Property<int>("idThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idThongBao"));

                    b.Property<bool>("daXem")
                        .HasColumnType("bit");

                    b.Property<int>("idNguoiNhan")
                        .HasColumnType("int");

                    b.Property<string>("lienKet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("noiDung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("idThongBao");

                    b.HasIndex("idNguoiNhan");

                    b.ToTable("THONGBAO");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ThongBaoHeThong", b =>
                {
                    b.Property<int>("idThongBaoHeThong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idThongBaoHeThong"));

                    b.Property<DateTime>("lanCuoiGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("maLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idThongBaoHeThong");

                    b.ToTable("THONGBAOHETHONG");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ThongSoKyThuat", b =>
                {
                    b.Property<int>("idThongSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idThongSo"));

                    b.Property<string>("tenThongSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idThongSo");

                    b.ToTable("THONGSOKYTHUAT");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ThuongHieu", b =>
                {
                    b.Property<int>("idThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idThuongHieu"));

                    b.Property<string>("tenThuongHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idThuongHieu");

                    b.ToTable("THUONGHIEU");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.TinhThanh", b =>
                {
                    b.Property<int>("idTinhThanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTinhThanh"));

                    b.Property<string>("tenTinhThanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTinhThanh");

                    b.ToTable("TINHTHANH");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.TrangThaiXacNhan", b =>
                {
                    b.Property<int>("idTrangThaiXacNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTrangThaiXacNhan"));

                    b.Property<string>("tenTrangThaiXacNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTrangThaiXacNhan");

                    b.ToTable("TRANGTHAIXACNHAN");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ViTri", b =>
                {
                    b.Property<int>("idViTri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idViTri"));

                    b.Property<decimal>("chieuCao")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("chieuDai")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("chieuRong")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("cot")
                        .HasColumnType("int");

                    b.Property<int>("daDung")
                        .HasColumnType("int");

                    b.Property<string>("day")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("idKhuVuc")
                        .HasColumnType("int");

                    b.Property<decimal>("sucChua")
                        .HasColumnType("decimal(20, 2)");

                    b.Property<int>("tang")
                        .HasColumnType("int");

                    b.Property<string>("trangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idViTri");

                    b.HasIndex("idKhuVuc");

                    b.ToTable("VITRI");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ViTriLuuTam", b =>
                {
                    b.Property<int>("idViTriLuuTam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idViTriLuuTam"));

                    b.Property<int>("idPhieuNhap")
                        .HasColumnType("int");

                    b.Property<int>("idSanPham")
                        .HasColumnType("int");

                    b.Property<int>("idViTri")
                        .HasColumnType("int");

                    b.Property<int>("soLuong")
                        .HasColumnType("int");

                    b.HasKey("idViTriLuuTam");

                    b.HasIndex("idPhieuNhap");

                    b.HasIndex("idSanPham");

                    b.HasIndex("idViTri");

                    b.ToTable("VITRILUUTAM");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.YeuCauKiemKe", b =>
                {
                    b.Property<int>("idYeuCauKiemKe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idYeuCauKiemKe"));

                    b.Property<string>("ghiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("mucDich")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ngayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("nguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("tenTruongBan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("tenUyVien1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("tenUyVien2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("trangThai")
                        .HasColumnType("int");

                    b.Property<string>("viTriKiemKe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idYeuCauKiemKe");

                    b.HasIndex("nguoiTao");

                    b.ToTable("YEUCAUKIEMKE");
                });

            modelBuilder.Entity("YeuCauXuatKho", b =>
                {
                    b.Property<int>("IdYeuCauXuatKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idYeuCauXuatKho");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdYeuCauXuatKho"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("diaChi");

                    b.Property<string>("HinhThucXuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hinhThucXuat");

                    b.Property<int>("IdDaiLy")
                        .HasColumnType("int")
                        .HasColumnName("idDaiLy");

                    b.Property<int>("IdDanhMuc")
                        .HasColumnType("int")
                        .HasColumnName("idDanhMuc");

                    b.Property<int>("IdDonViTinh")
                        .HasColumnType("int")
                        .HasColumnName("idDonViTinh");

                    b.Property<int>("IdTrangThaiXacNhan")
                        .HasColumnType("int")
                        .HasColumnName("idTrangThaiXacNhan");

                    b.Property<string>("LyDoXuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lyDoXuat");

                    b.Property<string>("MaPhieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("maPhieu");

                    b.Property<DateTime>("NgayYeuCau")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayYeuCau");

                    b.Property<string>("NguoiYeuCau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoiYeuCau");

                    b.Property<string>("PhuongThucVanChuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phuongThucVanChuyen");

                    b.Property<int>("idNguoiTao")
                        .HasColumnType("int")
                        .HasColumnName("idNguoiTao");

                    b.HasKey("IdYeuCauXuatKho");

                    b.HasIndex("IdDaiLy");

                    b.HasIndex("IdDanhMuc");

                    b.HasIndex("IdDonViTinh");

                    b.HasIndex("IdTrangThaiXacNhan");

                    b.HasIndex("idNguoiTao");

                    b.ToTable("YEUCAUXUATKHO");
                });

            modelBuilder.Entity("ChiTietPhieuNhap", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.PhieuNhap", null)
                        .WithMany("ChiTietPhieuNhap")
                        .HasForeignKey("PhieuNhapidPhieuNhap");

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.PhieuNhap", "PhieuNhap")
                        .WithMany()
                        .HasForeignKey("idPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PhieuNhap");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("PhieuXuat", b =>
                {
                    b.HasOne("YeuCauXuatKho", "YeuCauXuatKho")
                        .WithMany()
                        .HasForeignKey("IdYeuCauXuatKho");

                    b.Navigation("YeuCauXuatKho");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ChiTietKiemKe", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.KiemKe", "KiemKe")
                        .WithMany("ChiTietKiemKe")
                        .HasForeignKey("idKiemKe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.ViTri", "ViTri")
                        .WithMany()
                        .HasForeignKey("idViTri")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KiemKe");

                    b.Navigation("SanPham");

                    b.Navigation("ViTri");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ChiTietLuuTru", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.LoHang", "LoHang")
                        .WithMany()
                        .HasForeignKey("idLoHang");

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.PhieuNhap", "PhieuNhap")
                        .WithMany()
                        .HasForeignKey("idPhieuNhap")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.ViTri", "ViTri")
                        .WithMany()
                        .HasForeignKey("idViTri")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoHang");

                    b.Navigation("PhieuNhap");

                    b.Navigation("SanPham");

                    b.Navigation("ViTri");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ChiTietPhieuXuat", b =>
                {
                    b.HasOne("PhieuXuat", "PhieuXuat")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("IdPhieuXuat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("IdSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.ViTri", "ViTri")
                        .WithMany()
                        .HasForeignKey("IdViTri")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuXuat");

                    b.Navigation("SanPham");

                    b.Navigation("ViTri");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ChiTietThongSoKyThuat", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.ThongSoKyThuat", "ThongSoKyThuat")
                        .WithMany("ChiTietThongSoKyThuat")
                        .HasForeignKey("idThongSo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("ThongSoKyThuat");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ChiTietYeuCauKiemKe", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.YeuCauKiemKe", "YeuCauKiemKe")
                        .WithMany("ChiTietYeuCau")
                        .HasForeignKey("idYeuCauKiemKe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("YeuCauKiemKe");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ChiTietYeuCauXuatKho", b =>
                {
                    b.HasOne("YeuCauXuatKho", null)
                        .WithMany("ChiTietYeuCauXuatKhos")
                        .HasForeignKey("YeuCauXuatKhoIdYeuCauXuatKho");

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("YeuCauXuatKho", "YeuCauXuatKho")
                        .WithMany()
                        .HasForeignKey("idYeuCauXuatKho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("YeuCauXuatKho");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.KiemKe", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.YeuCauKiemKe", "YeuCauKiemKe")
                        .WithMany()
                        .HasForeignKey("idYeuCauKiemKe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YeuCauKiemKe");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.LoHang", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("idNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.PhieuNhap", "PhieuNhap")
                        .WithMany()
                        .HasForeignKey("idPhieuNhap")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.NhaCungCap", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.PhuongXa", "PhuongXa")
                        .WithMany()
                        .HasForeignKey("idPhuongXa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhuongXa");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.PhieuNhap", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("idNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("idTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.PhuongXa", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.QuanHuyen", "QuanHuyen")
                        .WithMany()
                        .HasForeignKey("idQuanHuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuanHuyen");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.QuanHuyen", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.TinhThanh", "TinhThanh")
                        .WithMany()
                        .HasForeignKey("idTinhThanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TinhThanh");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.SanPham", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.DanhMuc", "DanhMuc")
                        .WithMany()
                        .HasForeignKey("idDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DonViTinh", "DonViTinh")
                        .WithMany()
                        .HasForeignKey("idDonViTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("idNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.ThuongHieu", "ThuongHieu")
                        .WithMany()
                        .HasForeignKey("idThuongHieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("DonViTinh");

                    b.Navigation("NhaCungCap");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.SanPham_ThongSo", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.ThongSoKyThuat", "ThongSoKyThuat")
                        .WithMany()
                        .HasForeignKey("idThongSoKyThuat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("ThongSoKyThuat");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.ChucVu", "ChucVu")
                        .WithMany()
                        .HasForeignKey("idChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.DaiLy", "DaiLy")
                        .WithMany()
                        .HasForeignKey("idDaiLy");

                    b.Navigation("ChucVu");

                    b.Navigation("DaiLy");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ThongBao", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("idNguoiNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ViTri", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.KhuVuc", "KhuVuc")
                        .WithMany("ViTris")
                        .HasForeignKey("idKhuVuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuVuc");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ViTriLuuTam", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.PhieuNhap", "PhieuNhap")
                        .WithMany()
                        .HasForeignKey("idPhieuNhap")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("idSanPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.ViTri", "ViTri")
                        .WithMany()
                        .HasForeignKey("idViTri")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhieuNhap");

                    b.Navigation("SanPham");

                    b.Navigation("ViTri");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.YeuCauKiemKe", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.TaiKhoan", "NguoiTaoTaiKhoan")
                        .WithMany()
                        .HasForeignKey("nguoiTao");

                    b.Navigation("NguoiTaoTaiKhoan");
                });

            modelBuilder.Entity("YeuCauXuatKho", b =>
                {
                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.DaiLy", "DaiLy")
                        .WithMany()
                        .HasForeignKey("IdDaiLy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.DanhMuc", "DanhMuc")
                        .WithMany()
                        .HasForeignKey("IdDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DonViTinh", "DonViTinh")
                        .WithMany()
                        .HasForeignKey("IdDonViTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.TrangThaiXacNhan", "TrangThaiXacNhan")
                        .WithMany()
                        .HasForeignKey("IdTrangThaiXacNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHangFPTShop.server.Models.TaiKhoan", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("idNguoiTao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaiLy");

                    b.Navigation("DanhMuc");

                    b.Navigation("DonViTinh");

                    b.Navigation("NguoiTao");

                    b.Navigation("TrangThaiXacNhan");
                });

            modelBuilder.Entity("PhieuXuat", b =>
                {
                    b.Navigation("ChiTietPhieuXuats");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.KhuVuc", b =>
                {
                    b.Navigation("ViTris");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.KiemKe", b =>
                {
                    b.Navigation("ChiTietKiemKe");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhap");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.ThongSoKyThuat", b =>
                {
                    b.Navigation("ChiTietThongSoKyThuat");
                });

            modelBuilder.Entity("QuanLyKhoHangFPTShop.server.Models.YeuCauKiemKe", b =>
                {
                    b.Navigation("ChiTietYeuCau");
                });

            modelBuilder.Entity("YeuCauXuatKho", b =>
                {
                    b.Navigation("ChiTietYeuCauXuatKhos");
                });
#pragma warning restore 612, 618
        }
    }
}
